### ISSUE TITLE
Import error in pyvo

### ISSUE THREAD

**Issue by gkakumari** [astropy/pyvo#530]
Quite new to coding and github in general. I am trying to import the pyvo for my work and it shows some import error. Any help would be appreciated.
`import pyvo as vo`

`ImportError                               Traceback (most recent call last)
/tmp/ipykernel_4155/2276636013.py in <module>
----> 1 import pyvo as vo

~/.conda/envs/gk/lib/python3.9/site-packages/pyvo/__init__.py in <module>
     33 # ----------------------------------------------------------------------------
     34 
---> 35 from . import registry
     36 from .dal import ssa, sia, sla, scs, tap
     37 from . import auth

~/.conda/envs/gk/lib/python3.9/site-packages/pyvo/registry/__init__.py in <module>
      6 """
      7 
----> 8 from .regtap import search, ivoid2service, get_RegTAP_query, choose_RegTAP_service
      9 
     10 from .rtcons import (Constraint,

~/.conda/envs/gk/lib/python3.9/site-packages/pyvo/registry/regtap.py in <module>
     28 import numpy
     29 
---> 30 from . import rtcons
     31 from ..dal import scs, sia, sia2, ssa, sla, tap, query as dalq
     32 from ..io.vosi import vodataservice

~/.conda/envs/gk/lib/python3.9/site-packages/pyvo/registry/rtcons.py in <module>
     18 import numpy
     19 
---> 20 from ..dal import query as dalq
     21 from ..utils import vocabularies
     22 from .import regtap

~/.conda/envs/gk/lib/python3.9/site-packages/pyvo/dal/__init__.py in <module>
      1 # Licensed under a 3-clause BSD style license - see LICENSE.rst
----> 2 from .sia import search as imagesearch
      3 from .sia2 import search as imagesearch2
      4 from .ssa import search as spectrumsearch
      5 from .sla import search as linesearch

~/.conda/envs/gk/lib/python3.9/site-packages/pyvo/dal/sia.py in <module>
     37 from astropy.units import Quantity, Unit
     38 
---> 39 from .query import DALResults, DALQuery, DALService, Record
     40 from .mimetype import mime2extension
     41 from .adhoc import DatalinkResultsMixin, DatalinkRecordMixin, SodaRecordMixin

~/.conda/envs/gk/lib/python3.9/site-packages/pyvo/dal/query.py in <module>
     39 
     40 from .mimetype import mime_object_maker
---> 41 from .exceptions import (DALFormatError, DALServiceError, DALQueryError,
     42                          DALOverflowWarning)
     43 

ImportError: cannot import name 'DALOverflowWarning' from 'pyvo.dal.exceptions' `

I am using this in a conda env

**Comment by gkakumari** [comment]
The import seem to work well in the version 1.3 in my system without any error so far.

**Comment by msdemlei** [comment]
On Tue, Feb 27, 2024 at 11:12:57AM -0800, gkakumari wrote:
> ~/.conda/envs/gk/lib/python3.9/site-packages/pyvo/dal/query.py in <module>
>      39
>      40 from .mimetype import mime_object_maker
> ---> 41 from .exceptions import (DALFormatError, DALServiceError, DALQueryError,
>      42                          DALOverflowWarning)
>      43
>
> ImportError: cannot import name 'DALOverflowWarning' from 'pyvo.dal.exceptions' `

Quite bizarre.  So... can you have a look at
~/.conda/envs/gk/lib/python3.9/site-packages/pyvo/dal/exception.py
and see if it contains

  class DALOverflowWarning(UserWarning):
    pass

?  If it doesn't, there is a problem with your package.  If it does,
we have a new mystery...

**Comment by bsipocz** [comment]
Please try to uninstall and reinstall pyvo, this looks to be very much a local environment/installation issue rather than something inherent to the library itself.

**Comment by msdemlei** [comment]
@gkakumari -- does this problem persist? If not, can you close this bug?

**Comment by ManonMarchand** [comment]
Closing for now, but don't hesitate to open an other issue if you still have problems.
